# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DO!dobo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'ImageSlideshow', '~> 1.6'
    pod "ImageSlideshow/Alamofire"
    pod "ImageSlideshow/Kingfisher"
    pod 'SwiftyJSON'
    pod 'GooglePlaces'
    pod 'SilentScrolly'

  # Pods for DO!dobo

end
